config/routes.rb
Rails.application.routes.draw do
  # get 'home', to: 'pages#home'
  # get 'about', to: 'pages#about'
 
  # root 'pages#home'
  # root 'pages#about'

  get 'students/index'
  get 'students/show'
  get 'students/edit'
  get 'students/new'

  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about

  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end


  def new
    @student = Student.new
  end

  def create 
    student = Student.create(student_params)
    redirect_to students_path
  end
  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    redirect_to students_path
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end

  private
  def student_params
    params.require(:student).permit(:mahs, :ten, :lop, :masach, :tensach, :tacgia, :tusach, :sobm, :ngaymuon, :ngaytra, :songay)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main>
      <%= render 'partials/header' %>
      <%= yield %>
      <%= render 'partials/footer' %>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1>About page</h1>
  <%= link_to "Home", root_path%>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h1>Home page</h1>
  <%= link_to "About me", about_path%>
</div>

app/views/partials/_footer.html.erb
<div class="container">
  <footer class="py-3 my-4">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
      </ul>
      <p class="text-center text-muted">© 2022 Company, Inc</p>
    </footer>
</div>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
  
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      
       <ul class="navbar-nav">
          <li class="nav-item ">
          <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Nguyen Minh Hieu
          </a>
        </li>
         
      </ul>
    </div>
  </div>
</nav>

app/views/students/edit.html.erb
<h3 class="text-center">Cập nhật sinh viên</h3>
<div class="container">
    <div class="col-md-12">
    <%= form_with model: @student do |f|%>
<%= f.text_field :mahs, placeholder:"Nhap ma hoc sinh", class:"form-control"%>
<br>
<%= f.text_field :ten, placeholder:"Nhap ten", class:"form-control"%>
<br>
<%= f.text_field :lop, placeholder:"Nhap lop", class:"form-control"%>
<br>
<%= f.text_field :masach, placeholder:"Nhap ma sach", class:"form-control"%><br>
<%= f.text_field :tensach, placeholder:"Nhap ten sach", class:"form-control"%><br>
<%= f.text_field :tacgia, placeholder:"Nhap tac gia", class:"form-control"%><br>
<%= f.text_field :tusach, placeholder:"Nhap tu sach", class:"form-control"%><br>
<%= f.text_field :sobm, placeholder:"Nhap sobm", class:"form-control"%><br>
<%= f.text_field :ngaymuon, placeholder:"Nhap ngay muon", class:"form-control"%><br>
<%= f.text_field :ngaytra, placeholder:"Nhap ngay tra", class:"form-control"%><br>
<%= f.text_field :songay, placeholder:"Nhap so ngay", class:"form-control"%><br>
<%= f.submit %>
<% end %>
</div>
</div>

app/views/students/index.html.erb
<a href="/students/new" class="btn btn-sm btn-primary mb-2 ml-3">Thêm mới</a>

<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
  <tr>
    <th>STT</th>
    <th>MHS</th>
    <th>Họ và tên</th>
    <th>Lớp</th>
    <th>Mã sách</th>
    <th>Tên sách</th>
    <th>Tên tác giả</th>
    <th>Tủ sách</th>
    <th>Số BM</th>
    <th>Ngày mượn</th>
    <th>Ngày trả</th>
    <th>Số ngày</th>
    <th>Quản lý</th>
  </tr>
  </thead>

  <tbody>
   <% @index=0 %>
  <% @students.each do |student_120| %>
  <% @index=@index+1%>
      <tr>
        <td>
            <% @index %>
        </td>

        <td><%= student_120.mahs %></td>
        <td><%= link_to student_120.ten, student_path(student_120) %></td>
        <td><%= student_120.lop %></td>
        <td><%= student_120.masach %></td>
        <td><%= student_120.tensach %></td>
        <td><%= student_120.tacgia %></td>
        <td><%= student_120.tusach %></td>
        <td><%= student_120.sobm %></td>
        <td><%= student_120.ngaymuon %></td>
        <td><%= student_120.ngaytra %></td>
        <td><%= student_120.songay %></td>

        <td>
        <td><%= link_to 'Sửa',edit_student_path(student_120), method: 'get', class:"btn btn-info" %></td>
          <td><%= link_to 'Xoá', student_path(student_120), method: 'delete', class:"btn btn-danger"  %></td>
        </td>
      
      </tr>
  <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<h3 class="text-center">Thêm mới sinh viên</h3>
<div class="container">
    <div class="col-md-12">
    <%= form_with model: @student do |f|%>
<%= f.text_field :mahs, placeholder:"Nhap ma hoc sinh", class:"form-control"%>
<br>
<%= f.text_field :ten, placeholder:"Nhap ten", class:"form-control"%>
<br>
<%= f.text_field :lop, placeholder:"Nhap lop", class:"form-control"%>
<br>
<%= f.text_field :masach, placeholder:"Nhap ma sach", class:"form-control"%><br>
<%= f.text_field :tensach, placeholder:"Nhap ten sach", class:"form-control"%><br>
<%= f.text_field :tacgia, placeholder:"Nhap tac gia", class:"form-control"%><br>
<%= f.text_field :tusach, placeholder:"Nhap tu sach", class:"form-control"%><br>
<%= f.text_field :sobm, placeholder:"Nhap sobm", class:"form-control"%><br>
<%= f.text_field :ngaymuon, placeholder:"Nhap ngay muon", class:"form-control"%><br>
<%= f.text_field :ngaytra, placeholder:"Nhap ngay tra", class:"form-control"%><br>
<%= f.text_field :songay, placeholder:"Nhap so ngay", class:"form-control"%><br>
<%= f.submit %>
<% end %>
</div>
</div>

app/views/students/show.html.erb
<h1>Student Details</h1>
<p><%= @student.ten %></p>